# Generated by Django 4.2 on 2023-09-16 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_metric', to='lab_app.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'laboratory',
                'verbose_name_plural': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=5, max_digits=15)),
                ('indicator_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab_app.indicatormetric')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lab_app.test')),
            ],
            options={
                'verbose_name': 'scores',
                'verbose_name_plural': 'scores',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('min_score', models.DecimalField(decimal_places=5, max_digits=15)),
                ('max_score', models.DecimalField(decimal_places=5, max_digits=15)),
                ('indicator_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab_app.indicatormetric')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status')),
            ],
            options={
                'verbose_name': 'references',
                'verbose_name_plural': 'references',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=255)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status'),
        ),
        migrations.AddField(
            model_name='indicatormetric',
            name='metric',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab_app.metric'),
        ),
        migrations.AddField(
            model_name='indicatormetric',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lab_app.status'),
        ),
    ]
